apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: demo
    spec:
      containers:
      - name: demo
        image: mycluster.icp:8500/default/devops/demo:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 443
        volumeMounts:
        - name: devops-back
          mountPath: "/deployments/config"
          readOnly: true
      volumes:
      - name: demo
        configMap:
          name: demo
          items:
          - key: application.properties
            path: application.properties
