apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    run: demo
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30088
    name: http
  selector:
    run: demo
